DATA:
  data_name: s3dis
  data_root: dataset/s3dis/trainval_fullarea
  test_area: 5
  classes: 13
  fea_dim: 6
  voxel_size: 0.04
  voxel_max: 80000
  loop: 30

TRAIN:
  arch: pointtransformer_seg_repro_skip
  use_amp: True
  use_xyz: True
  sync_bn: True
  ignore_label: 255
  #label_weight: [19.2,16.5,27.8,1.7,2.0,2.5,4.7,3.3,3.4,0.4,6.3,1.2,10.5]
  train_gpu: [3,5,6,7]
  #train_gpu: [0,1,2,3]
  workers: 16  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 4  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.5
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  drop_rate: 0.5
  manual_seed: 7777
  print_freq: 1
  save_freq: 1
  save_path:
  weight:
  resume0:
  #resume: "/home/yansh/codes/point-transformer-master/exp/s3dis/org_0.70_0.77_0.90/model/model_best.pth"
  resume: 
  #resume0: "/home/yansh/codes/point-transformer-master/exp/s3dis_new/new_skip/model/model_best.pth" # path to initial weight (default: none)
  #resume: "/home/yansh/codes/point-transformer-master/exp/s3dis/org_0.70_0.77_0.90/model/model_best.pth" # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  #test_gpu: [4, 5, 6, 7]
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path: "/home/yansh/codes/point-transformer-master/exp/s3dis/org_0.70_0.77_0.90/model/model_best.pth"
  save_folder: 
  names_path: data/s3dis/s3dis_names.txt
